apiVersion: apps/v1
kind: Deployment
metadata:
  name: soloist-telegram
spec:
  replicas: ${REPLICAS}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: soloist-telegram
  template:
    metadata:
      labels:
        app: soloist-telegram
      annotations:
        commit.sha: "${GIT_COMMIT_SHA}"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: app
          image: $DEPLOY_IMAGE
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: POSTGRES_USER
              value: "${POSTGRES_USER}"
            - name: POSTGRES_PASSWORD
              value: "${POSTGRES_PASSWORD}"
            - name: TELEGRAM_BOT_TOKEN_APP
              value: "${TELEGRAM_BOT_TOKEN_APP}"
            - name: TELEGRAM_WEBHOOK_SECRET_TOKEN_APP
              value: "${TELEGRAM_WEBHOOK_SECRET_TOKEN_APP}"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5