apiVersion: v1
kind: Service
metadata:
  name: solo-leveling-telegram
spec:
  selector:
    app: solo-leveling-telegram
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http